\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename uni.info
@settitle Programming In Uni
@setchapternewpage odd
@c %**end of header

@macro venus
Uni
@end macro

@macro uni
Uni
@end macro

@ifinfo
Copyright @copyright{} 2004 Tianran Chen
@end ifinfo

@titlepage
@author Tianran Chen
@sp 10
@comment The title is printed in a large font.
@@center @titlefont{}

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2004 Tianran Chen
@end titlepage

@node Top, Installation, (dir), (dir)
@top

@menu
* Installation::                Install @uni to system
* Getting Start::               A quick walk through of the language
* Philosophy Of Uni::
* Basic Concepts::
* Metaprogramming In Uni::
* Manipulate Names::            
* Using Slots::
* Sample Natural English Dialect::
@end menu

@node Installation,  , Top, Top
@node Getting Start,  , Top, Top
@node Philosophy Of Uni,  , Top, Top
@node Basic Concepts,  , Top, Top
@node Metaprogramming In Uni,  , Top, Top
@node Manipulate Names,  , Top, Top
@node Using Slots,  , Top, Top
@node Sample Natural English Dialect,  , Top, Top

@c @include installation.texi
@c @include start.texi
@c @include concept.texi
@c @include primitive.texi
@c @include example.texi

@chapter Philosophy Of Uni
@chapter Metaprogramming In Uni

@bye
